### ISSUE TITLE
Library should enable mozlog programatically

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/go-mozlogrus#2]
Can mozlog format be enabled like this instead: `mozlogrus.Enable()`. I would like to switch [go-syncstorage](https://github.com/mozilla-services/go-syncstorage) to use this library. However, I have an env variable that enables mozlog. Disabling mozlog sometimes is helpful during development.

**Comment by leplatrem** [comment]
I find myself in a situation where the logger is still enabled just by importing it, and this is caused by these lines:

https://github.com/mozilla-services/go-mozlog/blob/master/mozlog.go#L30-L39

**Comment by oremj** [comment]
This is a tough one. Most of our apps depend on it being automatically enabled on import, so changing that would be difficult. It might be possible to add a disable function in mozlog.

**Comment by leplatrem** [comment]
> [...] so changing that would be difficult. 

I understand. But I was wondering if the use case described by @mostlygeek was solved actually.
